### ISSUE TITLE
Error in importing pycaw

### ISSUE THREAD

**Issue by Happy-Kunal** [kathir-t/GoogleMeet_CallAlerter#1]
```
$ python3 gm*
                               Traceback (most recent call last):            File "gm_script.py", line 7, in <module>
    from pycaw.pycaw import AudioUtilities, ISimpleAudioVolume
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/pycaw/pycaw.py", line 4, in <module>                                from ctypes import (HRESULT, POINTER, Structure, Union, c_float, c_longlong,        ImportError: cannot import name 'HRESULT' from 'ctypes' (/data/data/com.termux/files/usr/lib/python3.8/ctypes/__init__.py)
```

I had changed \\ with / as I am on Linux but it ***neither worked*** on my phone ***nor on Ubuntu ( computer )***
I had already installed all the dependencies manually !

**Comment by kathir-t** [comment]
There seems to be an error with `pycaw`. Are you using the latest version? Also, I noticed that you are using Python 3.8
I had developed on Python 3.7. That could also be the problem.

**Comment by Happy-Kunal** [comment]
Can you please commit the venv so that the program can be used independent of the systems installations , well I am using python 3.8.5 .

**Comment by kathir-t** [comment]
@Happy-Kunal I have added my environment's `requirements.txt` file. That should suffice. Do let me know if it helped.

**Comment by Happy-Kunal** [comment]
Thank you
